[package]
name = "lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "lantern_lang"

[dependencies]
parse = { path = "../parse" }
thiserror = { workspace = true }
anyhow = { workspace = true }
itertools = "0.13.0"

